package cn.edu.hzvtc.dao;

import cn.edu.hzvtc.pojo.Area;
import cn.edu.hzvtc.pojo.User;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface AreaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_area
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_area
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    int insert(Area record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_area
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    Area selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_area
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    List<Area> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_area
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    int updateByPrimaryKey(Area record);

    Area loginArea(@Param("id") int id);
}