package cn.edu.hzvtc.dao;

import cn.edu.hzvtc.pojo.MsgAnswer;
import java.util.List;

public interface MsgAnswerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_answer
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_answer
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    int insert(MsgAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_answer
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    MsgAnswer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_answer
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    List<MsgAnswer> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_answer
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    int updateByPrimaryKey(MsgAnswer record);
}