package cn.edu.hzvtc.dao;

import cn.edu.hzvtc.pojo.Msg;
import java.util.List;

public interface MsgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_info
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_info
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    int insert(Msg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_info
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    Msg selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_info
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    List<Msg> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_info
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    int updateByPrimaryKey(Msg record);
}