package cn.edu.hzvtc.dao;

import cn.edu.hzvtc.pojo.UserUnit;
import java.util.List;

public interface UserUnitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_unit
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_unit
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    int insert(UserUnit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_unit
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    UserUnit selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_unit
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    List<UserUnit> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_unit
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    int updateByPrimaryKey(UserUnit record);
}