package cn.edu.hzvtc.pojo;

import java.util.Date;

public class MsgAnswer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg_answer.id
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg_answer.msg_id
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    private Integer msgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg_answer.msg_receive_user_id
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    private Integer msgReceiveUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg_answer.msg_state
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    private Integer msgState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg_answer.msg_answer_time
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    private Date msgAnswerTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg_answer.msg_answer_content
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    private String msgAnswerContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg_answer.msg_vote
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    private Integer msgVote;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg_answer.msg_vote_reason
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    private String msgVoteReason;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg_answer.id
     *
     * @return the value of msg_answer.id
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg_answer.id
     *
     * @param id the value for msg_answer.id
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg_answer.msg_id
     *
     * @return the value of msg_answer.msg_id
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    public Integer getMsgId() {
        return msgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg_answer.msg_id
     *
     * @param msgId the value for msg_answer.msg_id
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    public void setMsgId(Integer msgId) {
        this.msgId = msgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg_answer.msg_receive_user_id
     *
     * @return the value of msg_answer.msg_receive_user_id
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    public Integer getMsgReceiveUserId() {
        return msgReceiveUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg_answer.msg_receive_user_id
     *
     * @param msgReceiveUserId the value for msg_answer.msg_receive_user_id
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    public void setMsgReceiveUserId(Integer msgReceiveUserId) {
        this.msgReceiveUserId = msgReceiveUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg_answer.msg_state
     *
     * @return the value of msg_answer.msg_state
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    public Integer getMsgState() {
        return msgState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg_answer.msg_state
     *
     * @param msgState the value for msg_answer.msg_state
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    public void setMsgState(Integer msgState) {
        this.msgState = msgState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg_answer.msg_answer_time
     *
     * @return the value of msg_answer.msg_answer_time
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    public Date getMsgAnswerTime() {
        return msgAnswerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg_answer.msg_answer_time
     *
     * @param msgAnswerTime the value for msg_answer.msg_answer_time
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    public void setMsgAnswerTime(Date msgAnswerTime) {
        this.msgAnswerTime = msgAnswerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg_answer.msg_answer_content
     *
     * @return the value of msg_answer.msg_answer_content
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    public String getMsgAnswerContent() {
        return msgAnswerContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg_answer.msg_answer_content
     *
     * @param msgAnswerContent the value for msg_answer.msg_answer_content
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    public void setMsgAnswerContent(String msgAnswerContent) {
        this.msgAnswerContent = msgAnswerContent == null ? null : msgAnswerContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg_answer.msg_vote
     *
     * @return the value of msg_answer.msg_vote
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    public Integer getMsgVote() {
        return msgVote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg_answer.msg_vote
     *
     * @param msgVote the value for msg_answer.msg_vote
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    public void setMsgVote(Integer msgVote) {
        this.msgVote = msgVote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg_answer.msg_vote_reason
     *
     * @return the value of msg_answer.msg_vote_reason
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    public String getMsgVoteReason() {
        return msgVoteReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg_answer.msg_vote_reason
     *
     * @param msgVoteReason the value for msg_answer.msg_vote_reason
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    public void setMsgVoteReason(String msgVoteReason) {
        this.msgVoteReason = msgVoteReason == null ? null : msgVoteReason.trim();
    }
}