package cn.edu.hzvtc.pojo;

public class Unit {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unit_info.id
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unit_info.unit_name
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    private String unitName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unit_info.unit_type_id
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    private Integer unitTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unit_info.unit_sort_num
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    private Integer unitSortNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unit_info.id
     *
     * @return the value of unit_info.id
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unit_info.id
     *
     * @param id the value for unit_info.id
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unit_info.unit_name
     *
     * @return the value of unit_info.unit_name
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    public String getUnitName() {
        return unitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unit_info.unit_name
     *
     * @param unitName the value for unit_info.unit_name
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    public void setUnitName(String unitName) {
        this.unitName = unitName == null ? null : unitName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unit_info.unit_type_id
     *
     * @return the value of unit_info.unit_type_id
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    public Integer getUnitTypeId() {
        return unitTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unit_info.unit_type_id
     *
     * @param unitTypeId the value for unit_info.unit_type_id
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    public void setUnitTypeId(Integer unitTypeId) {
        this.unitTypeId = unitTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unit_info.unit_sort_num
     *
     * @return the value of unit_info.unit_sort_num
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    public Integer getUnitSortNum() {
        return unitSortNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unit_info.unit_sort_num
     *
     * @param unitSortNum the value for unit_info.unit_sort_num
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    public void setUnitSortNum(Integer unitSortNum) {
        this.unitSortNum = unitSortNum;
    }
}