package cn.edu.hzvtc.pojo;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.id
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.user_name
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.user_password
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    private String userPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.user_operator_id
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    private Integer userOperatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.user_operator_time
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    private Date userOperatorTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.user_type
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    private Integer userType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.user_area_id
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    private Integer userAreaId;
    private String parentArea;
    private String parentAreaa;

    public String getParentArea() {
        return parentArea;
    }

    public void setParentArea(String parentArea) {
        this.parentArea = parentArea;
    }

    public String getParentAreaa() {
        return parentAreaa;
    }

    public void setParentAreaa(String parentAreaa) {
        this.parentAreaa = parentAreaa;
    }

    public String getAreaName() {
        return areaName;
    }

    public void setAreaName(String areaName) {
        this.areaName = areaName;
    }

    private String areaName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.id
     *
     * @return the value of sys_user.id
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.id
     *
     * @param id the value for sys_user.id
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.user_name
     *
     * @return the value of sys_user.user_name
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.user_name
     *
     * @param userName the value for sys_user.user_name
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.user_password
     *
     * @return the value of sys_user.user_password
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.user_password
     *
     * @param userPassword the value for sys_user.user_password
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword == null ? null : userPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.user_operator_id
     *
     * @return the value of sys_user.user_operator_id
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    public Integer getUserOperatorId() {
        return userOperatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.user_operator_id
     *
     * @param userOperatorId the value for sys_user.user_operator_id
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    public void setUserOperatorId(Integer userOperatorId) {
        this.userOperatorId = userOperatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.user_operator_time
     *
     * @return the value of sys_user.user_operator_time
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    public Date getUserOperatorTime() {
        return userOperatorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.user_operator_time
     *
     * @param userOperatorTime the value for sys_user.user_operator_time
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    public void setUserOperatorTime(Date userOperatorTime) {
        this.userOperatorTime = userOperatorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.user_type
     *
     * @return the value of sys_user.user_type
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    public Integer getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.user_type
     *
     * @param userType the value for sys_user.user_type
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    public void setUserType(Integer userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.user_area_id
     *
     * @return the value of sys_user.user_area_id
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    public Integer getUserAreaId() {
        return userAreaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.user_area_id
     *
     * @param userAreaId the value for sys_user.user_area_id
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    public void setUserAreaId(Integer userAreaId) {
        this.userAreaId = userAreaId;
    }
}