package cn.edu.hzvtc.pojo;

public class UserUnit {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_unit.id
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_unit.user_id
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_unit.unit_id
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    private Integer unitId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_unit.id
     *
     * @return the value of sys_user_unit.id
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_unit.id
     *
     * @param id the value for sys_user_unit.id
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_unit.user_id
     *
     * @return the value of sys_user_unit.user_id
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_unit.user_id
     *
     * @param userId the value for sys_user_unit.user_id
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_unit.unit_id
     *
     * @return the value of sys_user_unit.unit_id
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    public Integer getUnitId() {
        return unitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_unit.unit_id
     *
     * @param unitId the value for sys_user_unit.unit_id
     *
     * @mbg.generated Mon Sep 13 10:19:43 CST 2021
     */
    public void setUnitId(Integer unitId) {
        this.unitId = unitId;
    }
}